### ISSUE TITLE
Comparison of Optimal EECBS+ and CBSH2+RTC

### ISSUE THREAD

**Issue by furkancanturk** [Jiaoyang-Li/CBSH2-RTC#3]
Hi Jiaoyang,

I've read your papers introducing EECBS and CBSH2+RTC. I concluded that the optimal version of EECBS with all improvements (EECBS+ and w=1.0) is the same as CBSH2+RTC. I just wanted to ask if I missed something. Are there any differing mechanisms?

Thank you.

**Comment by Jiaoyang-Li** [comment]
CBSH2+RTC is slightly more advanced than EECBS+(w=1.0). The symmetry reasoning techniques used in EECBS+ are from the ICAPS 2020 paper "New Techniques for Pairwise Symmetry Breaking in Multi-Agent Path Finding", while those in CBSH2+RTC are from the AIJ 2021 journal paper "Pairwise Symmetry Reasoning for Multi-Agent Path Finding Search"
